allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  bufferutil: true
  core-js: true
  es5-ext: true
  esbuild: true
  protobufjs: true
  puppeteer: true
  sharp: true
  utf-8-validate: true